# Generated by Django 4.2 on 2023-05-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_games_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='game_raiting',
            new_name='game_rating',
        ),
    ]
